Repository canonical-web-and-design/docs.jujucharms.com, pull requests merged in 2019-05, with the labels that each got.

#13 Pretty URLs
  redirects.yaml
  requirements.txt
  templates/base.html
  templates/document.html
  webapp/app.py
  webapp/models.py
  webapp/tests/__init__.py
  webapp/tests/fixtures/__init__.py
  webapp/tests/fixtures/snapcraft_forum_mock.py
  webapp/tests/test_models.py
Labels: Review: Code +1, Review: QA +1

#14 Update header to match jaas.ai
  templates/base.html
Labels: Review: Code +1, Review: QA +1

#16 2.6 homepage
  templates/homepage.html
Labels: Review: Code +1, Review: QA +1

#17 More thorough redirects for old versions
  .circleci/config.yml
  package.json
  redirects.yaml
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#18 Fix nav styling on Chrome
  templates/base.html
Labels: Review: Code +1, Review: QA +1

#19 Remove Discourse lightbox markup
  templates/base.html
Labels: Review: Code +1, Review: QA +1

#20 Make external icons in nav accurate & add redirects
  redirects.yaml
  templates/base.html
Labels: Review: Code needed, Review: QA needed

#21 Make redirects more inclusive
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#23 Fix redirects for `/devel`, `/stable` etc.
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#24 Support for redirects in forum
  deleted.yaml
  redirects.yaml
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#25 Bump canonicalwebteam.discourse-docs to 0.4.0
  requirements.txt
Labels: Review: QA +1
